document.addEventListener("DOMContentLoaded", function() {

        // A animação da tela de abertura é 100% controlada pelo CSS.
            // O JavaScript só cuida das outras interatividades.

                // Inicializa o AOS (Animate On Scroll)
                    AOS.init({
                            duration: 1000,
                                    once: true,
                                        });

                                            // --- LÓGICA DO CARROSSEL (SWIPER) ---
                                                const timelineSwiperElement = document.querySelector('.timeline-swiper');
                                                    if (timelineSwiperElement) {
                                                            const timelineSwiper = new Swiper(timelineSwiperElement, {
                                                                        slidesPerView: 1,
                                                                                    spaceBetween: 30,
                                                                                                loop: false,
                                                                                                            pagination: { el: '.swiper-pagination', clickable: true },
                                                                                                                        navigation: { nextEl: '.swiper-button-next', prevEl: '.swiper-button-prev' },
                                                                                                                                    breakpoints: {
                                                                                                                                                    768: { slidesPerView: 2, spaceBetween: 40 },
                                                                                                                                                                    1024: { slidesPerView: 3, spaceBetween: 50 }
                                                                                                                                                                                },
                                                                                                                                                                                            on: {
                                                                                                                                                                                                            init: function() {
                                                                                                                                                                                                                                const activeSlide = this.slides[this.activeIndex];
                                                                                                                                                                                                                                                    if (activeSlide) {
                                                                                                                                                                                                                                                                            const videoToPlay = activeSlide.querySelector('video');
                                                                                                                                                                                                                                                                                                    if (videoToPlay) {
                                                                                                                                                                                                                                                                                                                                videoToPlay.play().catch(e => console.error("Vídeo inicial não pôde tocar automaticamente.", e));
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                            slideChangeTransitionEnd: function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                this.el.querySelectorAll('video').forEach(video => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        try { video.pause(); } catch (e) { }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const activeSlide = this.slides[this.activeIndex];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (activeSlide) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const videoToPlay = activeSlide.querySelector('video');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (videoToPlay) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                videoToPlay.currentTime = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            videoToPlay.play().catch(e => console.error("Erro no play do vídeo:", e));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // --- LÓGICA DA GALERIA (LIGHTBOX) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                lightbox.option({ 'resizeDuration': 200, 'wrapAround': true, 'albumLabel': "Foto %1 de %2" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (e) { console.warn("Aviso: Lightbox2 não encontrado."); }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // --- LÓGICA DO HEADER (SCROLL) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const headerElement = document.querySelector('.main-header');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (headerElement) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let lastScrollTop = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                window.addEventListener('scroll', function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let scrollTop = window.pageYOffset || document.documentElement.scrollTop;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        headerElement.style.transform = (scrollTop > lastScrollTop) ? 'translateY(-100%)' : 'translateY(0)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    lastScrollTop = scrollTop <= 0 ? 0 : scrollTop;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // --- LÓGICA DO CONTADOR DE TEMPO JUNTOS ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const startDate = new Date('2025-02-12T00:00:00'); // IMPORTANTE: A data de início!

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const daysEl = document.getElementById('days');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const hoursEl = document.getElementById('hours');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const minutesEl = document.getElementById('minutes');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const secondsEl = document.getElementById('seconds');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function updateCounter() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const now = new Date();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const difference = now - startDate;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Se a data ainda não chegou, mostra 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (difference < 0) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const days = Math.floor(difference / (1000 * 60 * 60 * 24));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const hours = Math.floor((difference / (1000 * 60 * 60)) % 24);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const minutes = Math.floor((difference / (1000 * 60)) % 60);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const seconds = Math.floor((difference / 1000) % 60);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Atualiza os números na tela
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            daysEl.innerText = days.toString().padStart(2, '0');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    hoursEl.innerText = hours.toString().padStart(2, '0');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            minutesEl.innerText = minutes.toString().padStart(2, '0');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    secondsEl.innerText = seconds.toString().padStart(2, '0');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Atualiza o contador a cada segundo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setInterval(updateCounter, 1000);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Chama a função uma vez para não começar com 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        updateCounter();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
